[package]
name = "pgp-sig2dot-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
categories = ["command-line-utilities", "visualization"]

[[bin]]
name = "pgp-sig2dot"
path = "src/main.rs"

[features]
map42 = [ "rustworkx-core" ]
nix = [ "rnix" ]

[dependencies]
pgp-sig2dot = { path = "../lib", version = "0.4.1" }
anyhow = { version = "1.0.86", features = ["backtrace"] }
clap = { version = "4.5.15", features = ["derive", "cargo"] }
clap-verbosity-flag = "3.0.2"
clap_complete = "4.5.14"
clap_mangen = "0.2.23"
clio = { version = "0.3.5", features = ["clap-parse", "curl", "http-curl"] }
env_logger = "0.11.5"
log = "0.4.22"
petgraph = { version = "0.8.2", features = ["rayon", "graphmap"], default-features = false }
serde = { version = "1.0.206", features = ["derive", "rc"] }
serde_json = "1.0.124"
tokio = "1.39.2"
sequoia-openpgp = { version = "2.1.0", default-features = false }
sequoia-net = "0.30.0"
format = "0.2.4"
futures = "0.3.31"
validator = "0.20.0"
reqwest = "0.12.24"
serialize_display_adapter_macro_derive = "0.2.0"
rustworkx-core = {  version = "0.17.1", optional = true }
rnix = { version = "0.12.0", optional = true }
